### ISSUE TITLE
WiFi is unable to obtain drone signals

### ISSUE THREAD

**Issue by zhang7249** [cyber-defence-campus/RemoteIDReceiver#3]
Hello, according to your tutorial, the demo has been successfully run in Raspberry Pi. You have also purchased the network cable and network card of EW-7881Un v2 that you recommended. The network card driver has also turned on Monitor mode and started the program. However, you cannot receive the remote message sent by the aircraft_ ID information, phenomenon is: no remote in sudo journalctl - f - u dsniffer_ ID information, only some log records of HTTP interface calls.

May I ask how to troubleshoot the problem.

I am in China, could it be that Chinese planes have not activated this feature.

![image](https://github.com/cyber-defence-campus/RemoteIDReceiver/assets/23712584/5238414e-1ed1-4d32-bd0f-adca272b7c95)

![image](https://github.com/cyber-defence-campus/RemoteIDReceiver/assets/23712584/7f7550d8-6d11-4bff-8f92-9bf8da1fd34c)

**Comment by zhang7249** [comment]
I tried to modify the drone_sniffer.py file and found that no logs with the zc word were output during runtime. The tcpdump - i wlx24698e2bf3db command allows you to see a lot of data on the console. Please help me, thank you!!!

```
def filter_frames(packet: Packet) -> None:
    """
    Method to filter Wi-Fi frames. Only frames containing a vendor specific element will not be filtered out
    directly. After the first filter a second one is applied which checks if an OUI of the vendor specific elements
    belongs to a format of an implemented handler. If not, it will be dismissed and the next Wi-Fi frame passes through
    the same filter logic.

    Args:
        packet (Packet): Wi-Fi frame.
    """
    logging.info(f"zc 1 - > {packet}")
    if packet.haslayer(Dot11Beacon):  # Monitor 802.11 beacon traffic
        logging.info(f"zc 2 - > {packet}")
        if packet.haslayer(Dot11EltVendorSpecific):  # check vendor specific ID -> 221
            logging.info(f"zc 3 - > {packet}")
            vendor_spec: Dot11EltVendorSpecific = packet.getlayer(Dot11EltVendorSpecific)
            logging.info(f"zc 4 - > {vendor_spec}")
            while vendor_spec:
                layer_oui = Parser.dec2hex(vendor_spec.oui)
                logging.info(f"zc 5 - > {layer_oui}")
                if handler.is_drone(layer_oui):
                    # parse header
                    remote_id = handler.parse(vendor_spec.info, layer_oui)
                    logging.info(f"zc 6 - > {remote_id}")
                    if remote_id:
                        serial = remote_id.serial_number
                        logging.info(f"Parsed Remote ID with serial number for: {serial}")

                        remote_id.add_home_loc(home_locations)
                        logging.info(f"Remote ID: {remote_id}")

                        save_drone_info(remote_id)
                    break
                else:
                    vendor_spec: Dot11EltVendorSpecific = vendor_spec.payload.getlayer(Dot11EltVendorSpecific)
                    continue
```

**Comment by llorencroma** [comment]
I would suggest you first test with the [Remote ID Spoofer](https://github.com/cyber-defence-campus/droneRemoteIDSpoofer)  whether there is a problem with the receiver . If you spoof, and the receiver displays detected drones, it could certainly be that the aircraft you are trying to receive information from does not implement the RemoteID feature (or at least not a RemoteID compliant with the format supported in this receiver).

**Comment by zhang7249** [comment]
Thank you for your reply! A great honor!

There is indeed a problem with the drone Remote IDspoofer sending. I bought two 7811Un network cards, a and b, which are both plugged into the same raspberry pie. A is used to receive and b is used to send. After the two processes started, the Remote IDReceiver did not receive data. Instead, using the same network card to send and receive data simultaneously. Is it related to my network card driver.

I bought Raspberry Pie 4b. Please give me your system and kernel information. I want to build the same system as you. First, make sure the communication between the two network cards is OK, and then confirm whether the aircraft will send remote messages_ ID.

PS: The system of Ubuntu desktop version kernel 5.10 does not support the monitoring mode of 7811Un network card.



Looking forward to your reply, thank you.

**Comment by llorencroma** [comment]
Could you try plugging one of the network cards into the laptop and run the spoofer from there while running the Receiver on the PI? or the other way around, as you wish. Remember to set the proper interface in monitor mode
`sudo ./interface-monitor.sh <interface-name>`

Then try spoofing few drone IDs `sudo python3 main.py -i <interface-name> -r 5`.

Also, have you configured the Google Maps API already on the receiver?

**Comment by zhang7249** [comment]
Okay, I'll try to separate the two network cards today. The main issue is that the driver for the network card is a bit difficult to handle. The network card driver on Ubuntu 22.04 and kernel 5.10 does not support turning on monitoring mode, so you need to reinstall the driver yourself. By the way, do you have any recommendations for installing the driver on your end? I am currently using the https://github.com/gglluukk/rtl8188eus .



I have configured the Google Maps API and can view maps through VPN. Haha, there's another episode in between. I can't register for Google's API because I don't have a foreign credit card. I searched on GitHub“ https://maps.googleapis.com/maps/api/js?key= ”Prefix, found a ready-made key in someone else's uploaded code, and used it directly...

I would still like a list of your environment configuration at that time, including system version, kernel, network card, Python - v, pip - v, and so on. Thank you! Wishing you good health and a happy family.

![image](https://github.com/cyber-defence-campus/RemoteIDReceiver/assets/23712584/f0e4c818-a532-45c1-8332-9196b28e0984)

**Comment by llorencroma** [comment]
According to this  [Edimax site ](https://edimax.freshdesk.com/support/solutions/articles/14000035492-how-to-resolve-ew-7811un-built-in-driver-issues-in-linux-kernel-v3-10-or-higher), you should not need to install additional drivers on your Linux kernel. The wifi network adapter should be plug and play. I will post list of my environment config in a separate comment.

**Comment by zhang7249** [comment]
It still doesn't work. Let's summarize it

Machine A  (ubuntu_x86)：
    The driver has been installed and the network card has been turned on in Monitor mode
    As you mentioned earlier, running the script "sudo python3 main. py - i<interface name>- r 5" did not reveal the existence of main. py, only spool_ Drones. py script.
    And the console shows that the data is already being sent, running the ifconfig command, 'TX packets 127', and the data is already being sent.
  
![image](https://github.com/cyber-defence-campus/RemoteIDReceiver/assets/23712584/52597376-f447-44ee-945d-c672b9277986)
![image](https://github.com/cyber-defence-campus/RemoteIDReceiver/assets/23712584/56bcb128-dc25-43e7-b7d1-feea8b0880a4)


Machine B (Raspberry Pi) ：

After installing the network card driver, running the RemoteIDReceiver project without any errors, sudo journalctl - f - u dsniffer, the console output is normal, and the web page is also accessed normally.

The content on the control is for me to modify drone_ The self added logs in the sniffer. py file indicate that data has been received. I just couldn't receive the data sent by A.

![image](https://github.com/cyber-defence-campus/RemoteIDReceiver/assets/23712584/6ba7379a-9106-4a8b-8213-c3bd3028e59c)



I really work hard and want to get this demo through. Your reply is very important to me!

**Comment by zhang7249** [comment]
I have good news for you. The demo has run smoothly and can be sent to the B network card via the A network card for acceptance.

Unfortunately, I regret to inform you that during actual testing on the aircraft, I was unable to receive the remote message_ ID, using M30T, M300, Mavic Air 2.

I have sent an email to DJI's customer service asking if China has opened remote_ The ID function, but I haven't received a response yet.

During the waiting process, I looked at the source code and had some questions that I need you to answer.

1
```
Id=None oui='FA: 0B: BC 'serial_ Number='Spoofed_ Serial_ 47538 'timestamp=date time. date time (2023, 9, 23, 15, 43, 31, 336426) lng=120.7283751 lat=31.2735666 altitude=None height=0 x_ Speed=0.0 y_ Speed=0.0 z_ Speed=None pitch=None roll=None yaw=0.0 pilot_ Lat=31.2756151 pilot_ Lng=120.7282845 home_ Lng=None home_ Lat=None uuid='Spoofed_ Serial_ 47538 'spoofed=False
```


The oui written in your code is FA: 0B: BC. I searched the IEEE official website for the registered MAC address of dji and found that it does not have this value. Moreover, when searching with this value, it was found to be empty. How did the value FA: 0B: BC come from. Please take a look at the bottom picture.



2. In actual operation, when the network card listening mode is first turned on, the code will receive the spool smoothly_ The event sent by drones.py, but after a while, it cannot be received. It is necessary to frequently open and close the network card on the web to make the network card receive the remote message again_ ID event.



Above are my two questions. Could you please reply? Thank you!
![image](https://github.com/cyber-defence-campus/RemoteIDReceiver/assets/23712584/0117acb7-4bce-4d5c-b78b-6df1555a09d6)
![image](https://github.com/cyber-defence-campus/RemoteIDReceiver/assets/23712584/ecc5510c-8a7e-40dc-b911-5f010f1ad0c6)

**Comment by llorencroma** [comment]
Happy to hear it worked for you. I don’t know why I can’t see your comments on Github anymore..

I can think of different reasons why you cannot receive it:
- The models are older versions that do not have the ID function built in.
- The ID function is not yet active in China (for instance in some european countries it has not been activated yet)

Regarding the source code:

1. The fa:0b:bc OUI was taken directly from a ID sent by a Parrot Anafi Thermal, which sends a ID compliant with the ASD-STAN. The tool does not consider all possible OUI’s and this list needs to be extended in the parsers.py file. For DJI we have the following OUI’s values:  ["60:60:1F", "48:1C:B9", "34:D2:62", "26:37:12”], also visible in the same parsers file.

2. he limitation of the network card is something that also occurred to us. Please note that as disclaimed in the README file of the repo, this was a student project and does not pretend to be a 100% reliable product. We would be happy if you want to contribute.


Bests

**Comment by llorencroma** [comment]
solved?

**Comment by zhang7249** [comment]
> 解决了？

There was no solution, but later I confirmed with DJI officials that Chinese aircraft do not support remoteid. Thank you for your concern.
