### ISSUE TITLE
Headless operating mode?

### ISSUE THREAD

**Issue by jonrau1** [cyber-defence-campus/RemoteIDReceiver#5]
Hello! This is a great project, was wondering if there was an easy way to run this "headless" or to perhaps stream drone locations as they are seen.

Want to use this as middleware with PyCOT to send Cursor on Target information about Drones and Pilots detected with Remote ID for CivTAK - it is a SA/C2 application used by a lot of volunteer SAR & fire/ems departments and not just the military.

For a similar use case, see this project that publishes ADS-B/Mode-S to ATAK as well so you can track aircraft in a search area / response area. https://adsbcot.readthedocs.io/en/latest/

**Comment by Lallirafn** [comment]
if you take a look at the code, the project has a good (but undocumented) API -and- a Web socket interface :) so yes, you can run this headless.  try /ws for the websocket or /api/drones/active to get all active drones and their current data for example....

**Comment by llorencroma** [comment]
You can find the API endpoints in `/Receiver/backend/dronesniffer/api.py`

**Comment by jonrau1** [comment]
Thanks both, figured as much.

Got the framework mostly working, my issue is now with Rpi5 running Ubuntu 23.10 - I am using an old TP-LINK TL-WN722Nv2 as an external dongle while on Wifi with the Pi, so it doesn't use `wlan0`, but it won't use the interface despite being able to detect it.

I see there is a `POST` endpoint for `/api/settings` - any docs what args that expects - is it enough just to pass an interface name?

Here is some junk code and responses, like I said, I am able to get the interfaces back just not assign them. I need to try it out over LAN and see what happens and try a few more interfaces, but I'll kick up a PR to add an extra arg. I'll be managing these remotely over S-Band or SATCOM, so I won't be able to always get to the remote sensors and need a way to override them.

Thanks in advance!

Shitty code:
```py
import requests
from time import sleep

def monitor():
    ifs = requests.get('http://192.168.0.211:8080/api/settings/interfaces')
    print(ifs.text)
    stat = requests.get('http://192.168.0.211:8080/api/settings')
    print(stat.text)
    r = requests.get('http://192.168.0.211:8080/api/drones/all')

    while True:
        print(r.status_code)
        print(r.text)
        sleep(2)

print(monitor())
```

Responses
```
["lo","eth0","wlan0","wlxd46e0e68489c"]
{"google_maps_api_key":null,"activity_offset_in_m":10,"drone_size_in_rem":5,"interfaces":[],"performance_mode":false}
200
[]
200
[]
200
[]
200
[]
```

**Comment by llorencroma** [comment]
As long as you can detect the interface you want to use via:

`ifs = requests.get('http://192.168.0.211:8080/api/settings/interfaces')`

Then you can just use the POST endpoint sending the following payload
`{"google_maps_api_key":"","activity_offset_in_m":10,"drone_size_in_rem":5,"interfaces":[],"performance_mode":false}`

The following should make the work:
```
import requests

# Define the endpoint URL
url = "http://0.0.0.0:80/api/settings"  # Replace "0.0.0.0" with your actual endpoint URL

# Define the payload
payload = {
    "google_maps_api_key": "your_api_key",
    "activity_offset_in_m": 10,
    "drone_size_in_rem": 5,
    "interfaces": [], #use you interfaces here
    "performance_mode": False
}

# Make the POST request
response = requests.post(url, json=payload)

# Check the response status code
if response.status_code == 200:
    print("POST request successful")
else:
    print(f"POST request failed with status code {response.status_code}")
    print(response.text)  # Print the response content if request failed
```

**Comment by jonrau1** [comment]
Awesome, a lot of the issues were misconfigured dongles and I only have access to much newer DJI drones but got it working with the spoofer and a few other models. Thanks again!
