### ISSUE TITLE
Out of memory when processing packets

### ISSUE THREAD

**Issue by afrs-us** [cyber-defence-campus/RemoteIDReceiver#7]
TO DUPLICATE
1 - Install on *nix system.
2 - Place interface in mon mode and permisc
3 - Start the remoteID app
4 - Open HTOP
5 - With each packet that is processed - Memory keeps creeping up until mem is gone, then swap will fill, then system will lock.

Can't put my finger on the cause yet.

**Comment by afrs-us** [comment]
Updated my version of python and that appeared to make the issue go away - Closing this item.

**Comment by llorencroma** [comment]
perfect, thanks
